version: "3.6"

services:
  indexer:
    image: ghcr.io/dipdup-io/celestia-indexer:${TAG:-master}
    build:
        dockerfile: build/indexer/Dockerfile
        context: .
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    depends_on:
      - db
    logging: &celestia-dipdup-logging
      options:
        max-size: 10m
        max-file: "5"

  api:
    restart: always
    image: ghcr.io/dipdup-io/celestia-api:${TAG:-master}
    build:
      context: .
      dockerfile: build/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 127.0.0.1:9876:9876
    logging: *celestia-dipdup-logging

  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    volumes:
      - db:/var/lib/postgres/data
      - /etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER:-dipdup}
      - POSTGRES_DB=${POSTGRES_DB:-celestia}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup -d celestia"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *celestia-dipdup-logging
    command:
      - "postgres"
      - "-c"
      - "config_file=${POSTGRES_CONFIG:-/etc/postgresql/postgresql.conf}"
volumes:
  db: